name: Testing
on: push

jobs:
  test_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run npm test
        run: |
          npm install
          npm test
